disabled_rules:
- trailing_whitespace
opt_in_rules:
- empty_count
- empty_string
- indentation_width
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 200
identifier_name:
    min_length: 2
reporter: "xcode"
